# Generated by Django 3.1.2 on 2020-10-28 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0005_auto_20201025_1819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='p_quantity',
        ),
        migrations.AddField(
            model_name='order_item',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
