# Generated by Django 3.1.2 on 2020-10-31 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0007_auto_20201028_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_item',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order_item',
            name='deliverred',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order_item',
            name='shipped',
            field=models.BooleanField(default=False),
        ),
    ]
