# Generated by Django 3.1.2 on 2020-10-31 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0008_auto_20201031_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_success',
            field=models.BooleanField(default=False),
        ),
    ]
