# Generated by Django 3.1.2 on 2020-10-31 11:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0009_order_order_success'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_item',
            name='date',
        ),
        migrations.AddField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 31, 11, 41, 18, 433370)),
        ),
    ]
