# Generated by Django 3.1.2 on 2020-10-31 11:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0010_auto_20201031_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 31, 11, 42, 6, 67542, tzinfo=utc)),
        ),
    ]
