# Generated by Django 3.1.2 on 2020-10-31 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0012_auto_20201031_1142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_item',
            name='quantity',
        ),
        migrations.AddField(
            model_name='order',
            name='order_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order_quantity',
            name='order_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='pantry.order'),
        ),
    ]
