# Generated by Django 3.1.2 on 2020-11-01 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0014_auto_20201101_0606'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_address',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='order',
            name='order_city',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='order_phone',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='order_state',
            field=models.CharField(default='', max_length=50),
        ),
    ]
