# Generated by Django 3.1.2 on 2020-11-01 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0015_auto_20201101_0808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_phone',
            field=models.BigIntegerField(default=0),
        ),
    ]
